### PR TITLE
keep errno value in Error enum

### LINKED ISSUE #143: inscrutable error when extracting archive to partition reaching limit of inodes
when extracting an archive to a partition with not enough inodes, I would expect an error along the lines of "No space left on device". Instead I get `INTERNAL ERROR: Function 'archive_write_data_block' invoked with archive structure in state 'header', should be in state 'data'` which is hard to interpret.

Steps to reproduce:
consider the following test program:

```
fn main() {
    use compress_tools::*;
    use std::fs::File;

    let mut source = File::open(&std::env::args().nth(1).unwrap()).unwrap();
    let dest = std::path::PathBuf::from(std::env::args().nth(2).unwrap());

    uncompress_archive(&mut source, &dest, Ownership::Ignore).unwrap();

}
```

compiled into `/tmp/bar/target/debug/bar`

Consider the following archive:

[0avnvyc7pkcr4pjqws7hwpy87m6wlnjc-make-4.4.1.tar.gz](https://github.com/user-attachments/files/26908204/0avnvyc7pkcr4pjqws7hwpy87m6wlnjc-make-4.4.1.tar.gz)

To simulate a full partition, I mount a tmpfs of limited to 10 inodes and unpack into it:
```
$  unshare -r -m sh -exc 'mount -t tmpfs -o size=10M,nr_inodes=10 tmpfs /tmp/foo; exec "$@"' wrapper target/debug/bar /nix/store/0avnvyc7pkcr4pjqws7hwpy87m6wlnjc-make-4.4.1.tar.gz /tmp/foo
+ mount -t tmpfs -o size=10M,nr_inodes=10 tmpfs /tmp/foo
+ exec target/debug/bar /nix/store/0avnvyc7pkcr4pjqws7hwpy87m6wlnjc-make-4.4.1.tar.gz /tmp/foo

thread 'main' (660098) panicked at src/main.rs:8:63:
called `Result::unwrap()` on an `Err` value: Extraction("INTERNAL ERROR: Function 'archive_write_data_block' invoked with archive structure in state 'header', should be in state 'data'")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
doing so with nr_inodes=1000 works fine

### PR DESCRIPTION
**Pull request by symphorien**
My goal is to make code calling uncompress_archive able to distinguish No space left on device from other error conditions. This is related to https://github.com/OSSystems/compress-tools-rs/issues/143 .

With this change, the error goes from:

```
thread 'main' (1282548) panicked at src/main.rs:8:63:
called `Result::unwrap()` on an `Err` value: Extraction("Can't create '/tmp/foo/make-4.4.1/NEWS'")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

to

```
thread 'main' (1287751) panicked at src/main.rs:8:63:
called `Result::unwrap()` on an `Err` value: ExtractionIo { code: Os { code: 28, kind: StorageFull, message: "No space left on device" }, details: "Can't create '/tmp/foo/make-4.4.1/NEWS'" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

which is much more explanatory. Besides, calling code can now inspect the cause of the error:
```
if let Err(e) = uncompress_archive(&mut source, &dest, Ownership::Ignore) {
      if let Some(ioerror) =  e.source().and_then(|s| s.downcast_ref::<std::io::Error>()) {
          if ioerror.kind() == std::io::ErrorKind::StorageFull {
              println!("detected storage full")
          }
      }
  }
```

Fixes: https://github.com/OSSystems/compress-tools-rs/issues/143

### CODE REVIEW

**Review by otavio — COMMENTED** [review]
Thanks for picking this up — the direction is right, and the `#[error(source)]` wiring so callers can downcast to `io::Error` is exactly what issue #143 needs.

A few things to address before merge:

### 1. Stray `'` in the `Io` Display string
```rust
#[display(fmt = "IO error: {_0}'")]
Io(#[error(source)] io::Error),
```
The closing `'` has no mate — output renders as `IO error: No such file or directory'`. Suggest `"IO error: {_0}"` or `"IO error: '{_0}'"` for consistency with the other variants.

### 2. `ExtractionIo` Display phrasing reads awkwardly
`"IO error during extraction error: {code}: '{details}'"` contains "error ... error". Something like `"Extraction IO error: {code}: '{details}'"` matches the tone of the existing `Extraction error: '...'`.

### 3. Avoid the silent re-routing by widening `Extraction` instead of adding a new variant
As written, a libarchive failure that has *both* an error string and a non-zero errno used to produce `Error::Extraction(text)` and will now produce `Error::ExtractionIo { .. }`. Any downstream code pattern-matching on `Err(Error::Extraction(_))` to catch "any extraction failure" silently stops matching those cases. `#[non_exhaustive]` softens this (callers must carry wildcards on the enum), but specific-variant arms will still quietly miss the ENOSPC path — which is exactly the case people care about.

A cleaner alternative is to keep a single `Extraction` variant and attach the optional errno to it:

```rust
#[display(fmt = "Extraction error: '{details}'")]
Extraction {
    details: String,
    #[error(source)]
    code: Option<io::Error>,
},
```

Then `From<*mut ffi::archive>` always returns `Error::Extraction { details, code }` whenever libarchive provided a string, whether or not there is also an errno. Callers who previously matched `Error::Extraction(_)` still match; callers who want the errno either destructure `code` or walk `err.source()` and downcast to `io::Error` — same as the example in the PR description.

Trade-off: this is a source-breaking shape change (existing `Error::Extraction(s)` patterns must become `Error::Extraction { details, .. }`), but it's a one-line compile-time fix rather than a silent rerouting, and it leaves the "which variant you get" behavior stable.

If you prefer to keep the two-variant design, please add a **Changed** entry to `CHANGES.md` noting that some errors that used to surface as `Error::Extraction` now surface as `Error::ExtractionIo`, so downstream consumers aren't surprised.

### 4. Please add a test covering the new shape
`tests/disk_full_test.rs` currently only checks `result.is_err()`. Since the whole point of this PR is that callers can inspect the errno, it would be great to lock that guarantee in — e.g. assert that the returned error's `source()` downcasts to an `io::Error` whose `kind() == ErrorKind::StorageFull` (or, with the widened-variant approach, destructure `Error::Extraction { code: Some(e), .. }` and check the same). That ensures a future refactor can't silently regress the behavior this PR is adding.

Happy to re-review once those are in.

**Comment by symphorien** [comment]
Thank you for your review. I think I have addressed all your remarks. Note that for point 4 (adding a test) I had to increase msrv from 1.82 to 1.83 as std::io::ErrorKind::StorageFull was introduced in rust 1.83.

**Comment by otavio** [comment]
Thanks — the core change is great. A few follow-ups before merging:

### 1. CI MSRV also needs bumping (or drop the MSRV bump)

`rust-version` in `Cargo.toml` isn't the only place the MSRV is pinned — the CI matrix lists `1.82.0 # MSRV` in four workflows:

- `.github/workflows/linux.yml:17`
- `.github/workflows/macos.yml:17`
- `.github/workflows/windows.yml:17`
- `.github/workflows/code_style.yml:34`

If you keep the bump to 1.83, please update those lines too so CI actually exercises the declared MSRV. Otherwise CI still builds against 1.82 and the declared MSRV drifts from what's verified.

Alternatively — since `ErrorKind::StorageFull` is only used in the new test — consider avoiding the bump entirely by comparing the raw errno instead (the crate already depends on `libc`):

```rust
if ioerror.raw_os_error() == Some(libc::ENOSPC) { OK } else { BUG_REPRODUCED }
```

That keeps MSRV at 1.82 and removes the CI-matrix churn.

### 2. `Display` impl: use `format_args!`, and split on `code`

Current:

```rust
#[display("Extraction error: {} '{}'", code.as_ref().map(|e| e.to_string()).unwrap_or("<unknown error>".to_string()), details)]
```

Two issues:

- `e.to_string()` and `"<unknown error>".to_string()` both allocate on every `Display` call. `format_args!` / the inline formatter avoid the allocation.
- When `code` is `None` we *do* have a description (`details`) — rendering `Extraction error: <unknown error> 'Can't create …'` reads as if we have nothing, which is misleading.

Suggested shape — separate arms so each case reads naturally:

```rust
// with code
"Extraction error: {details}: {code}"
// without code
"Extraction error: {details}"
```

(derive_more supports conditional display via a custom impl, or you can split into two helper branches — whichever is cleanest.)

### 3. Doc comment on the variant

```rust
/// An error whose description stems from `archive_errno` and `archive_error_string`
```

The per-field docs already explain this, and `code` being `Option` slightly contradicts the "stems from `archive_errno`" wording. I'd shorten or drop the variant-level doc and let the field docs carry the detail.

### 4. Test assertion is a bit shallow

The new child logic collapses three distinct outcomes — `Ok(())`, `Err` without an io source, and `Err` with the wrong `ErrorKind` — all into `BUG_REPRODUCED`. Functionally fine as a regression guard, but if this ever regresses in a new way you'll have to re-instrument the test to tell them apart. Consider distinct exit codes (or at least `eprintln!`-ing which branch fired before `process::exit`) so a future failure is self-diagnosing.

### 5. (Separately) This is a breaking change to `Error::Extraction`

Not blocking, and `#[non_exhaustive]` means it's technically allowed, but anyone matching `Error::Extraction(s)` breaks. Worth a 0.16.0 bump and a CHANGELOG line so downstream users see it coming — happy to handle that on the maintainer side if easier.

**Comment by symphorien** [comment]
about point 2 I will need your help, I have failed to find anything that compiles with format_args!

**Comment by symphorien** [comment]
I think I have addressed point 1 3 and 5. for point 4, tbh, the line `eprintln!("child: uncompress_archive result = {result:?}");` already satisfies your suggestion `(or at least eprintln!-ing which branch fired before process::exit`

File: src/error.rs [hunk 1]
```diff
@@ -11,10 +11,18 @@ pub type Result<T> = std::result::Result<T, Error>;
 #[derive(Display, From, Error, Debug)]
 #[non_exhaustive]
 pub enum Error {
-    #[display("Extraction error: '{}'", _0)]
-    Extraction(#[error(not(source))] String),
+    #[display("Extraction error: {} '{}'", code.as_ref().map(|e| e.to_string()).unwrap_or("<unknown error>".to_string()), details)]
```
Comment (otavio) [inline src/error.rs]: Two small nits, one verified: this is a 138-column single line that doesn't match the multi-line `#[display]` style used by `UnsupportedZipCompression` just below, and the fallback `.unwrap_or("<unknown error>".to_string())` always allocates even when `code.is_some()`. Both go away with `.as_deref()`:

```rust
#[display(
    "Extraction error: {} '{details}'",
    code.as_ref()
        .map(ToString::to_string)
        .as_deref()
        .unwrap_or("<unknown error>")
)]
```

I built this against your branch with `derive_more = 2.1` and confirmed byte-identical output (`Extraction error: No space left on device (os error 28) '...'` and `Extraction error: <unknown error> '...'`).

File: src/error.rs [hunk 2]
```diff
@@ -11,10 +11,18 @@ pub type Result<T> = std::result::Result<T, Error>;
...
+        /// The code stemming from `archive_errno`, unless it is not a valid value for `errno(3)`,
+        /// like `ARCHIVE_ERRNO_MISC`
+        #[error(source)]
+        code: Option<io::Error>,
+        /// The string returned by `archive_error_string`
+        details: String,
+    },
 
-    Io(io::Error),
+    #[display("IO error: {_0}")]
```
Comment (otavio) [inline src/error.rs]: Heads-up: before this PR, `Error::Io(_)` rendered as the inner `io::Error`'s `Display` directly (no prefix). Adding `#[display("IO error: {_0}")]` silently changes user-facing error strings for anyone that logs or pattern-matches on them. Was that intentional? If not, suggest dropping this `#[display]` attribute and letting the derive pass through the inner `io::Error` transparently, matching the pre-PR behavior. (This one is separate from the declared `Extraction` breaking change.)

File: src/error.rs [hunk 3]
```diff
@@ -62,20 +70,28 @@ pub(crate) fn archive_result_strict(value: i32, archive: *mut ffi::archive) -> R
...
-            if errno != 0 {
-                return io::Error::from_raw_os_error(errno).into();
-            }
+            code = if errno > 0 {
+                Some(io::Error::from_raw_os_error(errno))
+            } else {
+                // 0 (unexpected) or ARCHIVE_ERRNO_MISC which is not a valid value of errno(3)
+                None
+            };
+        }
```
Comment (otavio) [inline src/error.rs]: Non-blocking nit: this reads more idiomatically as a single `let` that captures the pair out of the `unsafe` block, which also keeps `details` and `code` immutable:

```rust
let (details, code) = unsafe {
    let error_string = ffi::archive_error_string(input);
    let details = (!error_string.is_null())
        .then(|| CStr::from_ptr(error_string).to_string_lossy().into_owned());
    let errno = ffi::archive_errno(input);
    let code = (errno > 0).then(|| io::Error::from_raw_os_error(errno));
    (details, code)
};
match (details, code) { /* unchanged */ }
```

Current form is correct — up to you.

**Review by otavio — COMMENTED** [review]
Thanks for tackling #143 — the `#[error(source)]` plumbing plus the errno downcast recipe in the PR description is exactly the API surface I want for consumers that need to branch on specific OS errors like ENOSPC. The `errno > 0` guard for `ARCHIVE_ERRNO_MISC` is a nice quiet correctness improvement over the old `!= 0` check too.

Three inline nits below (one of which is a user-visible behavior change, not just style).

Two things before merge:

1. **This is a breaking change** that isn't labeled as such in `CHANGES.md`. Both `Error::Extraction(String)` → `Error::Extraction { details, .. }` (tuple → struct; `#[non_exhaustive]` doesn't paper over the match-shape change for downstream consumers) and the newly added `#[error(source)]` on `Io` (callers of `.source()` on `Error::Io` previously got `None`; now they walk into the inner `io::Error`) are semver-major. Please call that out explicitly in the changelog entry — we'll bump to 0.16 on the next release.

2. **Please rebase onto current `master`** (`8089f85`). The PR base is `3303e9e`; #158 (encrypted-zip iteration) landed in the meantime. It doesn't touch `error.rs`, so the rebase should be clean.

File: src/error.rs (hunk 3 above)
Comment (symphorien) [reply src/error.rs]: done

File: src/error.rs (hunk 2 above)
Comment (symphorien) [reply src/error.rs]: add `Breaking:` prefix

File: src/error.rs (hunk 1 above)
Comment (symphorien) [reply src/error.rs]: split the line

**Comment by symphorien** [comment]
I found a way to have the display derive avoid heap allocations, so this should be good to go

File: src/error.rs (hunk 1 above)
Comment (otavio) [reply src/error.rs]: Take a look at the proposal I sent; I think it would be simpler than using the match and the conditional inside the display. The mapping I think that reduces the code in that use.

Comment (symphorien) [reply src/error.rs]: I did not take your proposal into account because:
- it contradicts your review complaining that the code "allocate[s] on every Display call"
- it contradicts your review "When code is None we do have a description (details) — rendering Extraction error: <unknown error> 'Can't create …' reads as if we have nothing, which is misleading."
